// Copyright 2020 FastWeGo
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

var apiConfigCrop = []ApiGroup{
	{
		Name:    `开发辅助`,
		Package: `util`,
		Apis: []Api{
			{
				Name:        "获取企业微信API域名IP段",
				Description: "API域名IP即qyapi.weixin.qq.com的解析地址，由开发者调用企业微信侧的接入IP。如果企业需要做防火墙配置，那么可以通过这个接口获取到所有相关的IP段。IP段有变更可能，当IP段变更时，新旧IP段会同时保留一段时间。建议企业每天定时拉取IP段，更新防火墙设置，避免因IP段变更导致网络不通。",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/get_api_domain_ip?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92520",
				FuncName:    "GetApiDomainIp",
			},
			{
				Name:        "获取企业微信服务器的ip段",
				Description: "企业微信在回调企业指定的URL时，是通过特定的IP发送出去的。如果企业需要做防火墙配置，那么可以通过这个接口获取到所有相关的IP段。",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/getcallbackip?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90238",
				FuncName:    "GetCallbackIp",
			},
		},
	},
	{
		Name:    `通讯录管理`,
		Package: `contact`,
		Apis: []Api{

			{
				Name:        "创建成员",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/user/create?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90195",
				FuncName:    "UserCreate",
			},
			{
				Name:        "读取成员",
				Description: "在通讯录同步助手中此接口可以读取企业通讯录的所有成员信息，而自建应用可以读取该应用设置的可见范围内的成员信息。",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/user/get?access_token=ACCESS_TOKEN&userid=USERID",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90196",
				FuncName:    "UserGet",
				GetParams: []Param{
					{Name: `userid`, Type: `string`},
				},
			},
			{
				Name:        "更新成员",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/user/update?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90197",
				FuncName:    "UserUpdate",
			},
			{
				Name:        "删除成员",
				Description: "",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/user/delete?access_token=ACCESS_TOKEN&userid=USERID",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90198",
				FuncName:    "UserDelete",
				GetParams: []Param{
					{Name: `userid`, Type: `string`},
				},
			},
			{
				Name:        "批量删除成员",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/user/batchdelete?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90199",
				FuncName:    "UserBatchDelete",
			},
			{
				Name:        "获取部门成员",
				Description: "",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/user/simplelist?access_token=ACCESS_TOKEN&department_id=DEPARTMENT_ID&fetch_child=FETCH_CHILD",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90200",
				FuncName:    "UserSimpleList",
				GetParams: []Param{
					{Name: `department_id`, Type: `string`},
					{Name: `fetch_child`, Type: `string`},
				},
			},
			{
				Name:        "获取部门成员详情",
				Description: "",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/user/list?access_token=ACCESS_TOKEN&department_id=DEPARTMENT_ID&fetch_child=FETCH_CHILD",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90201",
				FuncName:    "UserList",
				GetParams: []Param{
					{Name: `department_id`, Type: `string`},
					{Name: `fetch_child`, Type: `string`},
				},
			},
			{
				Name:        "userid与openid互换",
				Description: "注：需要成员使用微信登录企业微信或者关注微工作台（原企业号）才能转成openid;如果是外部联系人，请使用外部联系人openid转换转换openid",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/user/convert_to_openid?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90202",
				FuncName:    "ConvertToOpenid",
			},
			{
				Name:        "openid转userid",
				Description: "该接口主要应用于使用企业支付之后的结果查询。开发者需要知道某个结果事件的openid对应企业微信内成员的信息时，可以通过调用该接口进行转换查询。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/user/convert_to_userid?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90202",
				FuncName:    "ConvertToUserid",
			},
			{
				Name:        "二次验证",
				Description: "此接口可以满足安全性要求高的企业进行成员验证。开启二次验证后，当且仅当成员登录时，需跳转至企业自定义的页面进行验证。验证频率可在设置页面选择。开启二次验证方法如下图：企业在开启二次验证时，必须在管理端填写企业二次验证页面的url。当成员登录企业微信或关注微工作台（原企业号）进入企业时，会自动跳转到企业的验证页面。在跳转到企业的验证页面时，会带上如下参数：code=CODE。企业收到code后，使用“通讯录同步助手”调用接口“根据code获取成员信息”获取成员的userid。如果成员是首次加入企业，企业获取到userid，并验证了成员信息后，调用如下接口即可让成员成功加入企业。",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/user/authsucc?access_token=ACCESS_TOKEN&userid=USERID",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90203",
				FuncName:    "AuthSucc",
				GetParams: []Param{
					{Name: `userid`, Type: `string`},
				},
			},
			{
				Name:        "邀请成员",
				Description: "企业可通过接口批量邀请成员使用企业微信，邀请后将通过短信或邮件下发通知。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/batch/invite?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90975",
				FuncName:    "BatchInvite",
			},
			{
				Name:        "获取加入企业二维码",
				Description: "支持企业用户获取实时成员加入二维码。",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/corp/get_join_qrcode?access_token=ACCESS_TOKEN&size_type=SIZE_TYPE",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/91714",
				FuncName:    "GetJoinQrcode",
				GetParams: []Param{
					{Name: `size_type`, Type: `string`},
				},
			},
			{
				Name:        "获取企业活跃成员数",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/user/get_active_stat?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92714",
				FuncName:    "GetActiveStat",
			},
			{
				Name:        "创建部门",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/department/create?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90205",
				FuncName:    "DepartmentCreate",
			},
			{
				Name:        "更新部门",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/department/update?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90206",
				FuncName:    "DepartmentUpdate",
			},
			{
				Name:        "删除部门",
				Description: "",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/department/delete?access_token=ACCESS_TOKEN&id=ID",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90207",
				FuncName:    "DepartmentDelete",
				GetParams: []Param{
					{Name: `id`, Type: `string`},
				},
			},
			{
				Name:        "获取部门列表",
				Description: "",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/department/list?access_token=ACCESS_TOKEN&id=ID",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90208",
				FuncName:    "DepartmentList",
				GetParams: []Param{
					{Name: `id`, Type: `string`},
				},
			},
			{
				Name:        "创建标签",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/tag/create?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90210",
				FuncName:    "TagCreate",
			},
			{
				Name:        "更新标签名字",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/tag/update?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90211",
				FuncName:    "TagUpdate",
			},
			{
				Name:        "删除标签",
				Description: "",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/tag/delete?access_token=ACCESS_TOKEN&tagid=TAGID",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90212",
				FuncName:    "TagDelete",
				GetParams: []Param{
					{Name: `tagid`, Type: `string`},
				},
			},
			{
				Name:        "获取标签成员",
				Description: "",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/tag/get?access_token=ACCESS_TOKEN&tagid=TAGID",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90213",
				FuncName:    "TagGet",
				GetParams: []Param{
					{Name: `tagid`, Type: `string`},
				},
			},
			{
				Name:        "增加标签成员",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/tag/addtagusers?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90214",
				FuncName:    "TagAddTagUsers",
			},
			{
				Name:        "删除标签成员",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/tag/deltagusers?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90215",
				FuncName:    "TagDelTagUsers",
			},
			{
				Name:        "获取标签列表",
				Description: "",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/tag/list?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90216",
				FuncName:    "TagList",
			},
			{
				Name:        "增量更新成员",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/batch/syncuser?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90980",
				FuncName:    "SyncUser",
			},
			{
				Name:        "全量覆盖成员",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/batch/replaceuser?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90981",
				FuncName:    "ReplaceUser",
			},
			{
				Name:        "全量覆盖部门",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/batch/replaceparty?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90982",
				FuncName:    "ReplaceParty",
			},
			{
				Name:        "获取异步任务结果",
				Description: "",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/batch/getresult?access_token=ACCESS_TOKEN&jobid=JOBID",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90983",
				FuncName:    "JobGetResult",
				GetParams: []Param{
					{Name: `jobid`, Type: `string`},
				},
			},
		},
	},
	{
		Name:    `外部联系人管理`,
		Package: `externalcontact`,
		Apis: []Api{

			{
				Name:        "获取配置了客户联系功能的成员列表",
				Description: "企业和第三方服务商可通过此接口获取配置了客户联系功能的成员列表。",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/externalcontact/get_follow_user_list?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92571",
				FuncName:    "GetFollowUserList",
			},
			{
				Name:        "客户联系「联系我」管理",
				Description: "注意:通过API添加的「联系我」不会在管理端进行展示，每个企业可通过API最多配置50万个「联系我」。用户需要妥善存储返回的config_id，config_id丢失可能导致用户无法编辑或删除「联系我」。临时会话模式不占用「联系我」数量，但每日最多添加10万个，并且仅支持单人。临时会话模式的二维码，添加好友完成后该二维码即刻失效。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/add_contact_way?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92572",
				FuncName:    "AddContactWay",
			},
			{
				Name:        "客户联系「联系我」管理",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/get_contact_way?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92572",
				FuncName:    "GetContactWay",
			},
			{
				Name:        "更新企业已配置的「联系我」方式",
				Description: "更新企业配置的「联系我」二维码和「联系我」小程序按钮中的信息，如使用人员和备注等。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/update_contact_way?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92572",
				FuncName:    "UpdateContactWay",
			},
			{
				Name:        "客户联系「联系我」管理",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/del_contact_way?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92572",
				FuncName:    "DelContactWay",
			},
			{
				Name:        "客户联系「联系我」管理",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/close_temp_chat?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92572",
				FuncName:    "CloseTempChat",
			},
			{
				Name:        "获取客户列表",
				Description: "企业可通过此接口获取指定成员添加的客户列表。客户是指配置了客户联系功能的成员所添加的外部联系人。没有配置客户联系功能的成员，所添加的外部联系人将不会作为客户返回。",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/externalcontact/list?access_token=ACCESS_TOKEN&userid=USERID",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92113",
				FuncName:    "List",
				GetParams: []Param{
					{Name: `userid`, Type: `string`},
				},
			},
			{
				Name:        "获取客户详情",
				Description: "企业可通过此接口，根据外部联系人的userid（如何获取?），拉取客户详情。",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/externalcontact/get?access_token=ACCESS_TOKEN&external_userid=EXTERNAL_USERID",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92114",
				FuncName:    "Get",
				GetParams: []Param{
					{Name: `external_userid`, Type: `string`},
				},
			},
			{
				Name:        "修改客户备注信息",
				Description: "企业可通过此接口修改指定用户添加的客户的备注信息。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/remark?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92115",
				FuncName:    "Remark",
			},
			{
				Name:        "获取企业标签库",
				Description: "企业可通过此接口获取企业客户标签详情。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/get_corp_tag_list?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92117",
				FuncName:    "GetCorpTagList",
			},
			{
				Name:        "添加企业客户标签",
				Description: "企业可通过此接口向客户标签库中添加新的标签组和标签，每个企业最多可配置3000个企业标签。暂不支持第三方调用。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/add_corp_tag?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92117",
				FuncName:    "AddCorpTag",
			},
			{
				Name:        "编辑企业客户标签",
				Description: "企业可通过此接口编辑客户标签/标签组的名称或次序值。暂不支持第三方调用。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/edit_corp_tag?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92117",
				FuncName:    "EditCorpTag",
			},
			{
				Name:        "删除企业客户标签",
				Description: "企业可通过此接口删除客户标签库中的标签，或删除整个标签组。暂不支持第三方调用。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/del_corp_tag?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92117",
				FuncName:    "DelCorpTag",
			},
			{
				Name:        "编辑客户企业标签",
				Description: "企业可通过此接口为指定成员的客户添加上由企业统一配置的标签。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/mark_tag?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92118",
				FuncName:    "MarkTag",
			},
			{
				Name:        "获取客户群列表",
				Description: "该接口用于获取配置过客户群管理的客户群列表。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/groupchat/list?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92120",
				FuncName:    "GroupchatList",
			},
			{
				Name:        "获取客户群详情",
				Description: "通过客户群ID，获取详情。包括群名、群成员列表、群成员入群时间、入群方式。（客户群是由具有客户群使用权限的成员创建的外部群）",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/groupchat/get?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92122",
				FuncName:    "GroupchatGet",
			},
			{
				Name:        "添加企业群发消息任务",
				Description: "企业可通过此接口添加企业群发消息的任务并通知客服人员发送给相关客户或客户群。（注：企业微信终端需升级到2.7.5版本及以上）注意：调用该接口并不会直接发送消息给客户/客户群，需要相关的客服人员操作以后才会实际发送（客服人员的企业微信需要升级到2.7.5及以上版本）同一个企业每个自然月内仅可针对一个客户/客户群发送4条消息，超过限制的用户将会被忽略。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/add_msg_template?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92135",
				FuncName:    "AddMsgTemplate",
			},
			{
				Name:        "获取企业群发消息发送结果",
				Description: "企业可通过该接口获取到添加企业群发消息任务的群发发送结果。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/get_group_msg_result?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92136",
				FuncName:    "GetGroupMsgResult",
			},
			{
				Name:        "发送新客户欢迎语",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/send_welcome_msg?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92137",
				FuncName:    "SendWelcomeMsg",
			},
			{
				Name:        "添加群欢迎语素材",
				Description: "企业可通过此API向企业的群欢迎语素材库中添加素材。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/group_welcome_template/add?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92366",
				FuncName:    "GroupWelcomeTemplateAdd",
			},
			{
				Name:        "编辑群欢迎语素材",
				Description: "企业可通过此API编辑欢迎语素材库中的素材。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/group_welcome_template/edit?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92366",
				FuncName:    "GroupWelcomeTemplateEdit",
			},
			{
				Name:        "获取群欢迎语素材",
				Description: "企业可通过此API获取群欢迎语素材。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/group_welcome_template/get?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92366",
				FuncName:    "GroupWelcomeTemplateGet",
			},
			{
				Name:        "删除群欢迎语素材",
				Description: "企业可通过此API删除群欢迎语素材。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/group_welcome_template/del?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92366",
				FuncName:    "GroupWelcomeTemplateDel",
			},
			{
				Name:        "获取离职成员的客户列表",
				Description: "企业和第三方可通过此接口，获取所有离职成员的客户列表，并可进一步调用离职成员的外部联系人再分配接口将这些客户重新分配给其他企业成员。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/get_unassigned_list?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92124",
				FuncName:    "GetUnassignedList",
			},
			{
				Name:        "离职成员的外部联系人再分配",
				Description: "企业可通过此接口，将已离职成员的外部联系人分配给另一个成员接替联系。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/transfer?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92125",
				FuncName:    "Transfer",
			},
			{
				Name:        "离职成员的群再分配",
				Description: "企业可通过此接口，将已离职成员为群主的群，分配给另一个客服成员。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/groupchat/transfer?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92127",
				FuncName:    "GroupchatTransfer",
			},
			{
				Name:        "获取联系客户统计数据",
				Description: "企业可通过此接口获取成员联系客户的数据，包括发起申请数、新增客户数、聊天数、发送消息数和删除/拉黑成员的客户数等指标。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/get_user_behavior_data?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92132",
				FuncName:    "GetUserBehaviorData",
			},
			{
				Name:        "获取客户群统计数据",
				Description: "获取指定日期全天的统计数据。注意，企业微信仅存储180天的数据。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/groupchat/statistic?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92133",
				FuncName:    "GroupchatStatistic",
			},
		},
	},
	{
		Name:    `身份验证`,
		Package: `oauth`,
		Apis: []Api{
			{
				Name:        "构造网页授权链接",
				Description: "如果企业需要在打开的网页里面携带用户的身份信息，第一步需要构造如下的链接来获取code参数 ",
				Request:     "GET https://open.weixin.qq.com/connect/oauth2/authorize?appid=CORPID&redirect_uri=REDIRECT_URI&response_type=code&scope=snsapi_base&state=STATE#wechat_redirect",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/91022",
				FuncName:    "GetAuthorizeUrl",
				GetParams: []Param{
					{Name: `appid`, Type: `string`},
					{Name: `redirect_uri`, Type: `string`},
					{Name: `response_type`, Type: `string`},
					{Name: `scope`, Type: `string`},
					{Name: `state`, Type: `string`},
				},
			},
			{
				Name:        "获取访问用户身份",
				Description: "该接口用于根据code获取成员信息",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/user/getuserinfo?access_token=ACCESS_TOKEN&code=CODE",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/91023",
				FuncName:    "GetUserInfo",
				GetParams: []Param{
					{Name: `access_token`, Type: `string`},
					{Name: `code`, Type: `string`},
				},
			},
		},
	},
	{
		Name:    `身份验证`,
		Package: `verify`,
		Apis: []Api{

			{
				Name:        "获取访问用户身份",
				Description: "该接口用于根据code获取成员信息",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/user/getuserinfo?access_token=ACCESS_TOKEN&code=CODE参数说明：",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/91023",
				FuncName:    "GetUserInfo",
				GetParams: []Param{
					{Name: `code`, Type: `string`},
				},
			},
		},
	},
	{
		Name:    `应用管理`,
		Package: `app`,
		Apis: []Api{

			{
				Name:        "获取应用",
				Description: "",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/agent/get?access_token=ACCESS_TOKEN&agentid=AGENTID参数说明",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90227",
				FuncName:    "AgentGet",
				GetParams: []Param{
					{Name: `agentid`, Type: `string`},
				},
			},
			{
				Name:        "获取应用",
				Description: "",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/agent/list?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90227",
				FuncName:    "AgentList",
			},
			{
				Name:        "设置应用",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/agent/set?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90228",
				FuncName:    "AgentSet",
			},
			{
				Name:        "创建菜单",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/menu/create?access_token=ACCESS_TOKEN&agentid=AGENTID",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90231",
				FuncName:    "MenuCreate",
				GetParams: []Param{
					{Name: `agentid`, Type: `string`},
				},
			},
			{
				Name:        "获取菜单",
				Description: "",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/menu/get?access_token=ACCESS_TOKEN&agentid=AGENTID",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90232",
				FuncName:    "MenuGet",
				GetParams: []Param{
					{Name: `agentid`, Type: `string`},
				},
			},
			{
				Name:        "删除菜单",
				Description: "",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/menu/delete?access_token=ACCESS_TOKEN&agentid=AGENTID",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90233",
				FuncName:    "MenuDelete",
				GetParams: []Param{
					{Name: `agentid`, Type: `string`},
				},
			},
			{
				Name:        "设置工作台自定义展示",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/agent/set_workbench_template?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92535",
				FuncName:    "SetWorkbenchTemplate",
			},
			{
				Name:        "设置工作台自定义展示",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/agent/get_workbench_template?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92535",
				FuncName:    "GetWorkbenchTemplate",
			},
			{
				Name:        "设置工作台自定义展示",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/agent/set_workbench_data?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92535",
				FuncName:    "SetWorkbenchData",
			},
		},
	},
	{
		Name:    `消息推送`,
		Package: `message`,
		Apis: []Api{

			{
				Name:        "发送应用消息",
				Description: "应用支持推送文本、图片、视频、文件、图文等类型。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90236",
				FuncName:    "Send",
			},
			{
				Name:        "更新任务卡片消息状态",
				Description: "应用可以发送任务卡片消息，发送之后可再通过接口更新用户任务卡片消息的选择状态。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/message/update_taskcard?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/91579",
				FuncName:    "UpdateTaskcard",
			},

			{
				Name:        "创建群聊会话",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/appchat/create?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90245",
				FuncName:    "AppchatCreate",
			},
			{
				Name:        "修改群聊会话",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/appchat/update?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90246",
				FuncName:    "AppchatUpdate",
			},
			{
				Name:        "获取群聊会话",
				Description: "",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/appchat/get?access_token=ACCESS_TOKEN&chatid=CHATID",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90247",
				FuncName:    "AppchatGet",
				GetParams: []Param{
					{Name: `chatid`, Type: `string`},
				},
			},
			{
				Name:        "应用推送消息",
				Description: "应用支持推送文本、图片、视频、文件、图文等类型。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/appchat/send?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90248",
				FuncName:    "AppchatSend",
			},
			{
				Name:        "互联企业消息推送",
				Description: "互联企业的应用支持推送文本、图片、视频、文件、图文等类型。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/linkedcorp/message/send?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90250",
				FuncName:    "LinkedcorpMessageSend",
			},
			{
				Name:        "查询应用消息发送统计",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/message/get_statistics?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92369",
				FuncName:    "GetStatistics",
			},
		},
	},
	{
		Name:    `素材管理`,
		Package: `material`,
		Apis: []Api{

			{
				Name:        "上传临时素材",
				Description: "",
				Request:     "POST(@media) https://qyapi.weixin.qq.com/cgi-bin/media/upload?access_token=ACCESS_TOKEN&type=TYPE",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90253",
				FuncName:    "Upload",
				GetParams: []Param{
					{Name: `type`, Type: `string`},
				},
			},
			{
				Name:        "上传图片",
				Description: "",
				Request:     "POST(@media) https://qyapi.weixin.qq.com/cgi-bin/media/uploadimg?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90256",
				FuncName:    "UploadImg",
			},
			{
				Name:        "获取临时素材",
				Description: "",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/media/get?access_token=ACCESS_TOKEN&media_id=MEDIA_ID",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90254",
				FuncName:    "Get",
				GetParams: []Param{
					{Name: `media_id`, Type: `string`},
				},
			},
			{
				Name:        "获取高清语音素材",
				Description: "",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/media/get/jssdk?access_token=ACCESS_TOKEN&media_id=MEDIA_ID",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90255",
				FuncName:    "Jssdk",
				GetParams: []Param{
					{Name: `media_id`, Type: `string`},
				},
			},
		},
	},
	{
		Name:    `OA`,
		Package: `oa`,
		Apis: []Api{

			{
				Name:        "获取打卡数据",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/checkin/getcheckindata?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90262",
				FuncName:    "GetCheckinData",
			},
			{
				Name:        "获取打卡规则",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/checkin/getcheckinoption?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90263",
				FuncName:    "GetCheckinPption",
			},
			{
				Name:        "获取审批模板详情",
				Description: "企业可通过审批应用或自建应用Secret调用本接口，获取企业微信“审批应用”内指定审批模板的详情。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/oa/gettemplatedetail?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/91982",
				FuncName:    "GetTemplateDetail",
			},
			{
				Name:        "提交审批申请",
				Description: "企业可通过审批应用或自建应用Secret调用本接口，代应用可见范围内员工在企业微信“审批应用”内提交指定类型的审批申请。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/oa/applyevent?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/91853",
				FuncName:    "ApplyEvent",
			},
			{
				Name:        "批量获取审批单号",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/oa/getapprovalinfo?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/91816",
				FuncName:    "GetApprovalInfo",
			},
			{
				Name:        "获取审批申请详情",
				Description: "企业可通过审批应用或自建应用Secret调用本接口，根据审批单号查询企业微信“审批应用”的审批申请详情。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/oa/getapprovaldetail?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/91983",
				FuncName:    "GetApprovalDetail",
			},
			{
				Name:        "获取审批数据（旧）",
				Description: "通过本接口来获取公司一段时间内的审批记录。一次拉取调用最多拉取100个审批记录，可以通过多次拉取的方式来满足需求，但调用频率不可超过600次/分。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/corp/getapprovaldata?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/91530",
				FuncName:    "GetApprovalData",
			},
			{
				Name:        "获取公费电话拨打记录",
				Description: "企业可通过此接口，按时间范围拉取成功接通的公费电话拨打记录。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/dial/get_dial_record?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90267",
				FuncName:    "GetDialRecord",
			},
			{
				Name:        "查询自建应用审批单当前状态",
				Description: "开发者也可主动查询审批单的当前审批状态。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/corp/getopenapprovaldata?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90269",
				FuncName:    "GetOpenApprovalData",
			},
		},
	},
	{
		Name:    `日程`,
		Package: `calendar`,
		Apis: []Api{

			{
				Name:        "创建日历",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/oa/calendar/add?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92618",
				FuncName:    "CalendarAdd",
			},
			{
				Name:        "更新日历",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/oa/calendar/update?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92619",
				FuncName:    "CalendarUpdate",
			},
			{
				Name:        "获取日历",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/oa/calendar/get?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92621",
				FuncName:    "CalendarGet",
			},
			{
				Name:        "删除日历",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/oa/calendar/del?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92620",
				FuncName:    "CalendarDel",
			},
			{
				Name:        "创建日程",
				Description: "该接口用于在日历中创建一个日程。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/oa/schedule/add?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92622",
				FuncName:    "ScheduleAdd",
			},
			{
				Name:        "更新日程",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/oa/schedule/update?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92623",
				FuncName:    "ScheduleUpdate",
			},
			{
				Name:        "获取日程",
				Description: "该接口用于获取指定的日程详情。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/oa/schedule/get?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92624",
				FuncName:    "ScheduleGet",
			},
			{
				Name:        "取消日程",
				Description: "该接口用于取消指定的日程。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/oa/schedule/del?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92625",
				FuncName:    "ScheduleDel",
			},
			{
				Name:        "获取日历下的日程列表",
				Description: "该接口用于获取指定的日历下的日程列表。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/oa/schedule/get_by_calendar?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92626",
				FuncName:    "ScheduleGetByCalendar",
			},
		},
	},
	{
		Name:    `会议室`,
		Package: `meetingroom`,
		Apis: []Api{

			{
				Name:        "添加会议室",
				Description: "企业可通过此接口添加一个会议室。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/oa/meetingroom/add?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92793",
				FuncName:    "Add",
			},
			{
				Name:        "查询会议室",
				Description: "企业可通过此接口查询满足条件的会议室。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/oa/meetingroom/list?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92793",
				FuncName:    "List",
			},
			{
				Name:        "编辑会议室",
				Description: "企业可通过此接口编辑相关会议室的基本信息。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/oa/meetingroom/edit?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92793",
				FuncName:    "Edit",
			},
			{
				Name:        "删除会议室",
				Description: "企业可通过此接口删除指定的会议室。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/oa/meetingroom/del?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92793",
				FuncName:    "Del",
			},
			{
				Name:        "查询会议室的预定信息",
				Description: "企业可通过此接口查询相关会议室在指定时间段的预定情况，如是否已被预定，预定者的userid等信息，不支持跨天查询。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/oa/meetingroom/get_booking_info?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92794",
				FuncName:    "GetBookingInfo",
			},
			{
				Name:        "预定会议室",
				Description: "企业可通过此接口预定会议室并自动关联日程。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/oa/meetingroom/book?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92794",
				FuncName:    "Book",
			},
			{
				Name:        "取消预定会议室",
				Description: "企业可通过此接口取消会议室的预定",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/oa/meetingroom/cancel_book?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92794",
				FuncName:    "CancelBook",
			},
		},
	},
	{
		Name:    `企业支付`,
		Package: `pay`,
		Apis:    []Api{},
	},
	{
		Name:    `电子发票`,
		Package: `invoice`,
		Apis: []Api{

			{
				Name:        "查询电子发票",
				Description: "接口说明：报销方在获得用户选择的电子发票标识参数后，可以通过该接口查询电子发票的结构化信息，并获取发票PDF文件。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/card/invoice/reimburse/getinvoiceinfo?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90284",
				FuncName:    "GetInvoiceInfo",
			},
			{
				Name:        "更新发票状态",
				Description: "接口说明：报销企业和报销服务商可以通过该接口对某一张发票进行锁定、解锁和报销操作。各操作的业务含义及在用户端的表现如下：锁定：电子发票进入了企业的报销流程时应该执行锁定操作，执行锁定操作后的电子发票仍然会存在于用户卡包内，但无法重复提交报销。解锁：当电子发票由于各种原因，无法完成报销流程时，应执行解锁操作。执行锁定操作后的电子发票将恢复可以被提交的状态。报销：当电子发票报销完成后，应该使用本接口执行报销操作。执行报销操作后的电子发票将从用户的卡包中移除，用户可以在卡包的消息中查看到电子发票的核销信息。注意，报销为不可逆操作，请开发者慎重调用。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/card/invoice/reimburse/updateinvoicestatus?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90285",
				FuncName:    "UpdateInvoiceStatus",
			},
			{
				Name:        "批量更新发票状态",
				Description: "接口说明：发票平台可以通过该接口对某个成员的一批发票进行锁定、解锁和报销操作。注意，报销状态为不可逆状态，请开发者慎重调用。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/card/invoice/reimburse/updatestatusbatch?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90286",
				FuncName:    "UpdateStatusBatch",
			},
			{
				Name:        "批量查询电子发票",
				Description: "接口说明：报销方在获得用户选择的电子发票标识参数后，可以通过该接口批量查询电子发票的结构化信息。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/card/invoice/reimburse/getinvoiceinfobatch?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/90287",
				FuncName:    "GetInvoiceInfoBatch",
			},
		},
	},
	{
		Name:    `会话内容存档`,
		Package: `msgaudit`,
		Apis: []Api{

			{
				Name:        "获取会话内容",
				Description: "通过robot_id获取机器人的名称和创建者",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/msgaudit/get_robot_info?access_token=ACCESS_TOKEN&robot_id=ROBOT_ID",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/91774",
				FuncName:    "GetRobotInfo",
				GetParams: []Param{
					{Name: `robot_id`, Type: `string`},
				},
			},
			{
				Name:        "获取会话内容存档开启成员列表",
				Description: "企业可通过此接口，获取企业开启会话内容存档的成员列表",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/msgaudit/get_permit_user_list?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/91614",
				FuncName:    "GetPermitUserList",
			},
			{
				Name:        "获取会话内容存档内部群信息",
				Description: "企业可通过此接口，获取会话内容存档本企业的内部群信息，包括群名称、群主id、公告、群创建时间以及所有群成员的id与加入时间。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/msgaudit/groupchat/get?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92951",
				FuncName:    "GroupchatGet",
			},
		},
	},
	{
		Name:    `企业直播`,
		Package: `living`,
		Apis: []Api{

			{
				Name:        "获取成员直播ID列表",
				Description: "通过此接口可以获取指定成员指定时间内的所有直播ID",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/living/get_user_livingid?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92735",
				FuncName:    "GetUserLivingid",
			},
			{
				Name:        "获取直播详情",
				Description: "",
				Request:     "GET https://qyapi.weixin.qq.com/cgi-bin/living/get_living_info?access_token=ACCESS_TOKEN&livingid=LIVINGID",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92734",
				FuncName:    "GetLivingInfo",
				GetParams: []Param{
					{Name: `livingid`, Type: `string`},
				},
			},
			{
				Name:        "获取看直播统计",
				Description: "通过该接口可以获取所有观看直播的人员统计",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/living/get_watch_stat?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92736",
				FuncName:    "GetWatchStat",
			},
		},
	},
	{
		Name:    `健康上报`,
		Package: `health`,
		Apis: []Api{

			{
				Name:        "获取健康上报使用统计",
				Description: "",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/health/get_health_report_stat?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92747",
				FuncName:    "GetHealthReportStat",
			},
			{
				Name:        "获取健康上报任务ID列表",
				Description: "通过此接口可以获取企业当前正在运行的上报任务ID列表。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/health/get_report_jobids?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92749",
				FuncName:    "GetReportJobids",
			},
			{
				Name:        "获取健康上报任务详情",
				Description: "通过此接口可以获取指定的健康上报任务详情。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/health/get_report_job_info?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92751",
				FuncName:    "GetReportJobInfo",
			},
			{
				Name:        "获取用户填写答案",
				Description: "通过此接口可以获取指定的健康上报任务详情。",
				Request:     "POST https://qyapi.weixin.qq.com/cgi-bin/health/get_report_answer?access_token=ACCESS_TOKEN",
				See:         "https://work.weixin.qq.com/api/doc/90000/90135/92754",
				FuncName:    "GetReportAnswer",
			},
		},
	},
}
